name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Coveralls
        run: python -m pip install coveralls

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0a2

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: poetry install --with test --no-interaction --no-root

      - name: Install package
        run: poetry install --with test --no-interaction

      - name: Run tests
        run: poetry run pytest --cov-report= --cov=idleon_saver
        env:
          KIVY_GL_BACKEND: angle_sdl2

      - name: Publish coverage
        run: coveralls --service=github
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
